services:
  - type: web
    name: faceguard-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
